parameters:
  appSettings_urls_baseUrl: ''
  env: ''
  appSettings_azureBlob_connectionString: ''
  appSettings_eventStore_mongoDb_configuration: ''
  appSettings_store_mongoDb_configuration: ''
  appSettings_identity_adminEmail: ''
  appSettings_identity_AdminPassword: ''
  Build_sourcesDirectory: ''

steps:
- powershell: |
   $config = "{
     ""urls"": {
       ""baseUrl"": ""${{ parameters.appSettings_urls_baseUrl }}""
     },
   
     ""assetStore"": {
       ""type"": ""AzureBlob""
     },
   
     ""azureBlob"": {
       ""containerName"": ""${{ parameters.env }}-assetstore"",
       ""connectionString"": ""${{ parameters.appSettings_azureBlob_connectionString }}""
     },
   
     ""eventStore"": {
       ""mongoDb"": {
         ""configuration"": ""${{ parameters.appSettings_eventStore_mongoDb_configuration }}"",
         ""database"": ""${{ parameters.env }}_squidexeventdb""
       }
     },
   
     ""store"": {
       ""mongoDb"": {
         ""configuration"": ""${{ parameters.appSettings_store_mongoDb_configuration }}"",
         ""contentDatabase"": ""${{ parameters.env }}_squidexstorcontentdb"",
         ""database"": ""${{ parameters.env }}_squidexstoredb""
       }
     },
   
     ""identity"" : {
       ""googleClient"": """",
       ""googleSecret"": """",
       ""githubClient"": """",
       ""githubSecret"": """",
       ""microsoftClient"": """",
       ""microsoftSecret"": """",
       ""adminEmail"": ""${{ parameters.appSettings_identity_adminEmail }}"",
       ""AdminPassword"": ""${{ parameters.appSettings_identity_AdminPassword }}""
     }
   }
   "
   write-host $config
   set-content -value $config -path "${{ parameters.build_sourcesDirectory }}/src/Squidex/appsettings_${{ parameters.env }}_json"
  displayName: 'Save Appconfig'